name: dsp
channels:
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- appdirs=1.4.3=py_0
- appnope=0.1.0=py36_0
- arrow=0.10.0=py_1
- asn1crypto=0.22.0=py36_0
- attrs=17.2.0=py_1
- automat=0.6.0=py36_0
- binaryornot=0.4.4=py36_0
- bleach=2.0.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- constantly=15.1.0=py_0
- cookiecutter=1.6.0=py36_0
- cryptography=2.0.3=py36_0
- cssselect=1.0.1=py_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- future=0.16.0=py36_0
- html5lib=0.999999999=py36_0
- hyperlink=17.3.1=py_0
- icu=58.1=1
- idna=2.6=py36_1
- incremental=17.5.0=py_0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.3=py36_1
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jinja2-time=0.2.0=py36_1
- jpeg=9b=2
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=2
- libsodium=1.0.15=0
- libxml2=2.9.5=1
- libxslt=1.1.29=5
- lxml=4.1.1=py36_0
- markupsafe=1.0=py36_0
- mistune=0.8=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.2.1=py36_2
- openssl=1.0.2l=0
- pandas=0.21.0=py36_0
- pandoc=2.0.0.1=1
- pandocfilters=1.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- poyo=0.4.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pyasn1=0.3.7=py_0
- pyasn1-modules=0.1.5=py_0
- pycparser=2.18=py36_0
- pydispatcher=2.0.5=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=17.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- python=3.6.3=1
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- pyzmq=16.0.2=py36_2
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- scrapy=1.4.0=py36_0
- setuptools=36.6.0=py36_1
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py_1
- whichcraft=0.4.1=py36_0
- widgetsnbextension=3.0.6=py36_0
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- intel-openmp=2018.0.0=h68bdfb3_7
- libgfortran=3.0.1=h93005f0_2
- mkl=2018.0.0=h5ef208c_6
- numpy=1.13.3=py36h2cdce51_0
- parsel=1.2.0=py36_0
- queuelib=1.4.2=py36_0
- service_identity=17.0.0=py36_0
- twisted=17.9.0=py36h1a7ef6d_0
- w3lib=1.18.0=py36h63be7f5_0
- zope=1.0=py36_0
- zope.interface=4.4.3=py36h74e83c9_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - service-identity==17.0.0
prefix: //anaconda/envs/dsp

